# Generated by Django 4.2.19 on 2025-03-02 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ball_size', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('paddle_speed', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('paddle_size', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('ball_speed', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('ball_num', models.PositiveIntegerField(default=1)),
                ('timer', models.PositiveIntegerField(default=60)),
                ('score_board', models.BooleanField(default=True)),
                ('ball_multiplier_enabled', models.BooleanField(default=False)),
                ('background_song', models.CharField(default='default_song.mp3', max_length=255)),
                ('background_image', models.CharField(default='default_image.png', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
