# Generated by Django 4.2.19 on 2025-02-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournament_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score',
            new_name='final_score',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='max_players',
            new_name='max_participants',
        ),
    ]
