# Generated by Django 5.1.6 on 2025-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
