# Generated by Django 5.1.6 on 2025-02-23 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_otp_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='match_history',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='secret_key',
        ),
    ]
