# Generated by Django 4.2.19 on 2025-02-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='ball_multiplier_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
