# Generated by Django 5.1.6 on 2025-02-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_language',
            field=models.CharField(default='en', help_text="The user's preferred default language.", max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
